### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "id": 2,
    "private_key": "fcefwe"
}

###

GET https://localhost:8001
Authorization: Bearer 65B42392BA49F3FB64AE9844BA414
content-type: application/json

###

POST https://localhost:8001/buy
Content-Type: application/json

{
  "kp": "",
  "sol_ui": 0.01,
  "mint": "9N3FrUVUCPXSbqAdAffYP79sGS5wp3rU7V4XLQQCpump",
  "tp": 0.01,
  "sl": -0.01
}
