### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

POST http://localhost:5000/users
Content-Type: application/json

{
    "id": 2,
    "private_key": "fcefwe"
}

###

GET https://fmpowzsx5n3cqgmhoufynetisa0mavss.lambda-url.eu-west-2.on.aws/users
Authorization: Bearer 65B42392BA49F3FB64AE9844BA414
content-type: application/json

###

POST localhost:4000/buy
Content-Type: application/json

{
  "kp": "65fKKEPAf8CUUmbtTAaLudPXHW8ZigaDRFE3cdbQSgy7WdSNZv3eWfXChvLSM8NfSfxteLAFesbLa7FksNG6zwDu",
  "sol_ui": 0.01,
  "mint": "6tZNU9395v9Gm3JQeAcbLAte4uLJnDMavPdwo9HTpump",
  "tp": 0.01,
  "sl": -0.01
}
