pub mod constant;
pub mod digitalocean_droplet;
pub mod digitalocean_droplet_utils;
pub mod dns_manager;
pub mod ssh_executor;
pub mod user_api;
pub mod db;
pub mod amm_type;
// pub mod trade_type;
// pub mod trade_type;
// pub mod position;
// pub mod cmd;
// pub mod schema;
// pub mod rpc;
// pub mod trade_chan;
// pub mod program_log;
// pub mod websocket_server;
// pub mod jito_chan;
// pub mod net;
// pub mod solana;
// pub mod pump;
// pub mod trade;
// pub mod prompt_type;
// pub mod bg_chan;
// pub mod prompt_chan;
// pub mod type_dsl;
// pub mod app_user_type;
// pub mod web_server;
// pub mod chan;
// pub mod trade_impl;
// pub mod user;
