name: Install and Run Just

on:
  push: # Triggers the workflow on push events
    branches:
      - main # Specify the branches you want to trigger the workflow on
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  user-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal # Installs only the Rust CLI tools
          override: true

      - name: Install Just
        run: cargo install just

      - name: Run Justfile
        env:
          BASE64_ENV: ${{ secrets.BASE64_ENV }}
        run: |
          just --version
          just env
          BIN_NAME=user_api just run